<?php
$this->headTitle('Crea Automezzo');
$form = $this->form;
$form->prepare();
?>


<div class="page-header">
    <p>
        <a class="btn btn-default" href="
    <?= $this->url('elenco_automezzi'); ?>">
            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Indietro
        </a>
    </p>
    <div class="row">
        <div class="col-xs-12"><h1>Crea Automezzo</h1></div>
    </div>
</div>
<br>
<div id='creaautomezzo'>
    <?php
    echo $this->form()->openTag($form);

    foreach ($form as $element) {
        if ('submit' != $element->getAttribute('type') && 'hidden' != $element->getAttribute('type')){
            ?>
            <div class="row">
                <div class="col-xs-10">
                    <div class="form-group <?php if ($this->formElementErrors($element)){ echo "has-error";} ?>">
                        <label  class="col-md-3 control-label"><?php echo $element->getLabel(); ?></label>
                        <div class="col-md-<?php if(strpos($element->getAttribute('class'),'datepicker') !== false) echo"4"; else echo "4"; ?>">
                            <?php
                            if ('submit' != $element->getAttribute('type') && 'hidden' != $element->getAttribute('type')) {
                                echo $this->formElement($element);
                                if ($this->formElementErrors($element)) {
                                    $helper = $this->formElementErrors();
                                    $helper->setMessageOpenFormat('<div class="help-inline">');
                                    $helper->setMessageSeparatorString('</div><div class="help-inline">');
                                    $helper->setMessageCloseString('</div>');
                                    $helper->setTranslateMessages(true);

                                    echo $helper->render($element);
                                }
                            }
                            ?>

                        </div>
                        <div class="form-group col-md-3"><?php echo $element->getAttribute('suggerimento'); ?></div>
                    </div>
                </div>
            </div>
            <br>
            <?php
        }else{
            if('hidden' == $element->getAttribute('type')){
                echo $this->formElement($element);
            }
        }
    }
    ?>
</div>
<div class="row">
    <div class="col-xs-12">
        <?php
        echo $this->formElement($form->get('submit'));
        ?>
    </div>
</div>
</div>

<?php
echo $this->form()->closeTag();
?>
</div>



