Application\Entity\Filiale:
    type: entity
    table: filiale
    repositoryClass: Application\Repositories\Filiale
    id:
        codice:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codice
            generator:
                strategy: IDENTITY
    fields:
        indirizzo:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: indirizzo
        citta:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: citta
        cap:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: cap
    lifecycleCallbacks: {  }
