<?= $this->doctype() ?>

<html lang="it">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Powering-app')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- The styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/table.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/datepicker.css'))
            ->prependStylesheet($this->basePath('css/datatables.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/function.js'))
            ->prependFile($this->basePath('js/datepicker.min.js'))
            ->prependFile($this->basePath('js/locales/it.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/datatables.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
          <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/logocup.png') ?>" height="28" alt="Powering App <?= \Application\Module::VERSION ?>"/>&nbsp;
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home') ?>">Home</a></li>
                        <li><a href="<?php echo $this->url('elenco_automezzi') ?>">Automezzi</a></li>
                        <li><a href="<?php echo $this->url('elenco_filiali') ?>">Filiali</a></li>
                        <li><a href="<?php echo $this->url('chiamata_http') ?>">Http Post</a></li>
                    </ul>
                        <ul class="nav navbar-nav navbar-right">

					    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->partial('partial/flash.phtml', $this->flashMessenger()); ?>
            <?= $this->content ?>
        </div>
        <div class="container">
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> by Powering. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
