<?php
$this->headTitle('Dettaglio Filiale');
?>


<div class="page-header">
    <p>
        <a class="btn btn-default" href="
    <?= $this->url('elenco_filiali'); ?>">
            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Torna all'elenco
        </a>
    </p>
    <div class="row">
        <div class="col-xs-12"><h1>Filiale: <?php echo $obj->getCodice()." <br> ".$obj->getIndirizzo()." <br> ".$obj->getCap()." - ".$obj->getCitta(); ?></h1></div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12"><h1>Elenco Automezzi Collegati</h1></div>
</div>
<br>
<div class="row">
    <div class="table-responsive">
        <table class="table table-striped table-responsive" id="automezzi">
            <thead>
            <tr id="firstRow" role="row">
                <th>Codice</th>
                <th>Targa</th>
                <th>Marca</th>
                <th>Modello</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    var data = <?php echo $jsonData; ?>;
    $('#automezzi').DataTable( {
        data: data,
        language: {
            url: full+'/language/Italian.json'
        },
        columns: [
            { data: 'codice' , class: "col_md-1"},
            { data: 'targa' },
            { data: 'marca' },
            { data: 'modello' }
        ],
        "drawCallback": function( settings ) {
            var api = this.api();

            // Output the data for the visible rows to the browser's console
            //console.log( api.rows( {page:'current'} ).data() );
            var mydata = api.rows( {page:'current'} ).data();
        }
    } );
</script>