<div class="jumbotron">
    <div class="text-center">
        <h1><span class="zf-blue">Elenco Filiali</span></h1>
        <h3>Visualizza la lista delle filiali, i dettagli di ciascuna ed effettua operazioni di CRUD</h3>
    </div>
</div>
<!--<div class="row">
    <div class="col-md-8 text-center">
        <h3>Elenco Filiali</h3>
    </div>
</div>-->
<br><br>
<div class="row">
    <div class="col-md-2"><a class="btn btn-success" href="<?php echo $this->url('crea_filiale'); ?>"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Crea Filiale</a></div>
</div>
<br>

<div class="row">
    <div class="table-responsive">
        <table class="table table-striped table-responsive" id="filiali">
            <thead>
            <tr id="firstRow" role="row">
                <th>Codice</th>
                <th>Indirizzo</th>
                <th>Città</th>
                <th>CAP</th>
                <th>Azioni</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    var data = <?php echo $jsonData; ?>;
    $('#filiali').DataTable( {
        data: data,
        language: {
            url: full+'/language/Italian.json'
        },
        columns: [
            { data: 'codice' , class: "col_md-1"},
            { data: 'indirizzo' },
            { data: 'citta' },
            { data: 'cap' },
            { data: 'Azioni' ,
                orderable: false,
                defaultContent: "<?php
                    echo "<a class='btn btn-default modificalink'  href='".$this->url('modifica_filiale',array('codice'=>"xxxx"))."' title='modifica'   alt='modifica'><span class='glyphicon glyphicon-pencil'></span> Modifica</a>";
                    echo "&nbsp;&nbsp;&nbsp;";
                    echo "<a class='btn btn-danger cancellalink'  href='".$this->url('cancella_filiale',array('codice'=>"xxxx"))."' title='cancella'   alt='cancella'><span class='glyphicon glyphicon-remove'></span> Cancella</a>";
                    echo "&nbsp;&nbsp;&nbsp;";
                    echo "<a class='btn btn-primary dettagliolink'  href='".$this->url('dettaglio_filiale',array('codice'=>"xxxx"))."' title='dettaglio'   alt='dettaglio'><span class='glyphicon glyphicon-search'></span> Dettaglio</a>";

                    ?>"
            }
        ],
        "drawCallback": function( settings ) {
            var api = this.api();

            // Output the data for the visible rows to the browser's console
            //console.log( api.rows( {page:'current'} ).data() );
            var mydata = api.rows( {page:'current'} ).data();

            $('.modificalink').each(function(i,item){
                //console.log(mydata[i]);
                $(item).attr("href",$(item).attr("href").replace("xxxx",mydata[i].codice));

            });
            $('.cancellalink').each(function(i,item){
                //console.log(mydata[i]);
                $(item).attr("href",$(item).attr("href").replace("xxxx",mydata[i].codice));

            });
            $('.dettagliolink').each(function(i,item){
                //console.log(mydata[i]);
                $(item).attr("href",$(item).attr("href").replace("xxxx",mydata[i].codice));

            });
        }
    } );
</script>